language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - pip install ${DJANGO}
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt

script:  python manage.py test
env:
  - DJANGO="Django==1.11.*"
  - DJANGO="Django==2.0.*"
  - DJANGO="Django==2.1.*"
  - DJANGO="Django==2.2.*"
  - DJANGO="Django==3.0.*"
matrix:
  exclude:
    - python: 3.5
      env: DJANGO="Django==3.0.*"
